/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaPresentacion.CRUD.Categoria;
import CapaPresentacion.CRUD.Encargado;
import CapaPresentacion.CRUD.Hackathon;
import CapaPresentacion.CRUD.Organizador;
import CapaPresentacion.CRUD.Patrocinador;
import CapaPresentacion.Reportes.Estadisticas;
import CapaPresentacion.Reportes.General;
import CapaPresentacion.Reportes.HackathonPeriodo;
import CapaPresentacion.Reportes.HackathonTematica;
import java.awt.Color;

/**
 *
 * @author Rolo
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        this.rootPane.getContentPane().setBackground(Color.getHSBColor(122, 110, 238));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReportesBtn3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        HackatonList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        InscripcionesList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        OrganizadorBtn = new javax.swing.JButton();
        EncargadoBtn = new javax.swing.JButton();
        HackathonBtn = new javax.swing.JButton();
        PatrocinadorBtn = new javax.swing.JButton();
        CategoriaBtn = new javax.swing.JButton();
        RGBtn = new javax.swing.JButton();
        HTBtn = new javax.swing.JButton();
        HPBtn = new javax.swing.JButton();
        EBtn = new javax.swing.JButton();

        ReportesBtn3.setBackground(new java.awt.Color(102, 0, 0));
        ReportesBtn3.setForeground(new java.awt.Color(255, 255, 255));
        ReportesBtn3.setText("Reporte General");
        ReportesBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesBtn3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 0, 0));
        jButton5.setText("Organizador");

        jButton9.setBackground(new java.awt.Color(102, 0, 0));
        jButton9.setText("Hackathon por Temática");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hackathon CR");

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HACKATHON CR");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hackathon");

        HackatonList.setBackground(new java.awt.Color(133, 35, 35));
        HackatonList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HackatonList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(HackatonList);

        InscripcionesList.setBackground(new java.awt.Color(133, 35, 35));
        InscripcionesList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        InscripcionesList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(InscripcionesList);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inscripciones");

        OrganizadorBtn.setBackground(new java.awt.Color(102, 0, 0));
        OrganizadorBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        OrganizadorBtn.setForeground(new java.awt.Color(255, 255, 255));
        OrganizadorBtn.setText("Organizer");
        OrganizadorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrganizadorBtnActionPerformed(evt);
            }
        });

        EncargadoBtn.setBackground(new java.awt.Color(102, 0, 0));
        EncargadoBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EncargadoBtn.setForeground(new java.awt.Color(255, 255, 255));
        EncargadoBtn.setText("Attendant");
        EncargadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncargadoBtnActionPerformed(evt);
            }
        });

        HackathonBtn.setBackground(new java.awt.Color(102, 0, 0));
        HackathonBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HackathonBtn.setForeground(new java.awt.Color(255, 255, 255));
        HackathonBtn.setText("Hackathon");
        HackathonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HackathonBtnActionPerformed(evt);
            }
        });

        PatrocinadorBtn.setBackground(new java.awt.Color(102, 0, 0));
        PatrocinadorBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PatrocinadorBtn.setForeground(new java.awt.Color(255, 255, 255));
        PatrocinadorBtn.setText("Sponsor");
        PatrocinadorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatrocinadorBtnActionPerformed(evt);
            }
        });

        CategoriaBtn.setBackground(new java.awt.Color(102, 0, 0));
        CategoriaBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CategoriaBtn.setForeground(new java.awt.Color(255, 255, 255));
        CategoriaBtn.setText("Category");
        CategoriaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaBtnActionPerformed(evt);
            }
        });

        RGBtn.setBackground(new java.awt.Color(102, 0, 0));
        RGBtn.setForeground(new java.awt.Color(255, 255, 255));
        RGBtn.setText("General Report");
        RGBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGBtnActionPerformed(evt);
            }
        });

        HTBtn.setBackground(new java.awt.Color(102, 0, 0));
        HTBtn.setForeground(new java.awt.Color(255, 255, 255));
        HTBtn.setText("Hackathon by Topic");
        HTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HTBtnActionPerformed(evt);
            }
        });

        HPBtn.setBackground(new java.awt.Color(102, 0, 0));
        HPBtn.setForeground(new java.awt.Color(255, 255, 255));
        HPBtn.setText("Hackathon by Period");
        HPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPBtnActionPerformed(evt);
            }
        });

        EBtn.setBackground(new java.awt.Color(102, 0, 0));
        EBtn.setForeground(new java.awt.Color(255, 255, 255));
        EBtn.setText("Stats");
        EBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(OrganizadorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EncargadoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HackathonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PatrocinadorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CategoriaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RGBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HTBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HPBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrganizadorBtn)
                    .addComponent(EncargadoBtn)
                    .addComponent(HackathonBtn)
                    .addComponent(PatrocinadorBtn)
                    .addComponent(CategoriaBtn))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RGBtn)
                    .addComponent(HTBtn)
                    .addComponent(HPBtn)
                    .addComponent(EBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReportesBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportesBtn3ActionPerformed

    private void OrganizadorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrganizadorBtnActionPerformed
        new Organizador().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OrganizadorBtnActionPerformed

    private void EncargadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncargadoBtnActionPerformed
        new Encargado().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_EncargadoBtnActionPerformed

    private void HackathonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HackathonBtnActionPerformed
        new Hackathon().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_HackathonBtnActionPerformed

    private void PatrocinadorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatrocinadorBtnActionPerformed
        new Patrocinador().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_PatrocinadorBtnActionPerformed

    private void CategoriaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaBtnActionPerformed
        new Categoria().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaBtnActionPerformed

    private void RGBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGBtnActionPerformed
        new General().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_RGBtnActionPerformed

    private void HTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HTBtnActionPerformed
        new HackathonTematica().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_HTBtnActionPerformed

    private void HPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPBtnActionPerformed
        new HackathonPeriodo().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_HPBtnActionPerformed

    private void EBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EBtnActionPerformed
        new Estadisticas().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_EBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CategoriaBtn;
    private javax.swing.JButton EBtn;
    private javax.swing.JButton EncargadoBtn;
    private javax.swing.JButton HPBtn;
    private javax.swing.JButton HTBtn;
    private javax.swing.JButton HackathonBtn;
    private javax.swing.JList<String> HackatonList;
    private javax.swing.JList<String> InscripcionesList;
    private javax.swing.JButton OrganizadorBtn;
    private javax.swing.JButton PatrocinadorBtn;
    private javax.swing.JButton RGBtn;
    private javax.swing.JButton ReportesBtn3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
