/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion.CRUD;

import CRUD.Eliminacion;
import CRUD.Modificar;
import CRUD.Visualizacion;
import DataBase.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolo
 */
public class Hackathon extends javax.swing.JFrame {

    /**
     * Creates new form Hackathon
     */
    String id, name, organizer, attendant, topic, projectD, requirement, 
            category, hours, start, finish, website, email, first, second, third, sponsor;
    String filename = null;
    String filename2 = null;
    byte[] person_image=null;
    byte[] person_image2=null;
    public Hackathon() {
        this.rootPane.getContentPane().setBackground(Color.getHSBColor(122, 110, 238));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreTxtField15 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton3 = new javax.swing.JRadioButton();
        imagenLabel = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        BuscarBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        CodigoMTxtField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        ValorMTxtField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        CodigoETxtField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        HackatonList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CodigoTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        NombreTxtField = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        imagenLabel1 = new javax.swing.JLabel();
        BuscarBtn1 = new javax.swing.JButton();
        NombreTxtField3 = new javax.swing.JTextField();
        NombreTxtField4 = new javax.swing.JTextField();
        NombreTxtField7 = new javax.swing.JTextField();
        NombreTxtField8 = new javax.swing.JTextField();
        NombreTxtField9 = new javax.swing.JTextField();
        NombreTxtField10 = new javax.swing.JTextField();
        NombreTxtField11 = new javax.swing.JTextField();
        NombreTxtField12 = new javax.swing.JTextField();
        NombreTxtField13 = new javax.swing.JTextField();
        NombreTxtField14 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        NombreTxtField5 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        EdicionTxtField = new javax.swing.JTextField();

        NombreTxtField15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField15.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField15.setText("Premio 3er Lugar");
        NombreTxtField15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtField15MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hackathon CR");
        setResizable(false);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Organizer");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        imagenLabel.setBackground(new java.awt.Color(133, 35, 35));
        imagenLabel.setForeground(new java.awt.Color(255, 255, 255));
        imagenLabel.setText("                                     LOGO");
        imagenLabel.setOpaque(true);

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Topic");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        BuscarBtn.setBackground(new java.awt.Color(102, 0, 0));
        BuscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        BuscarBtn.setText("Search Image");
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });

        CodigoMTxtField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CodigoMTxtField.setForeground(new java.awt.Color(153, 153, 153));
        CodigoMTxtField.setText("ID");
        CodigoMTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodigoMTxtFieldMouseClicked(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        ValorMTxtField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ValorMTxtField.setForeground(new java.awt.Color(153, 153, 153));
        ValorMTxtField.setText("Modified Value");
        ValorMTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ValorMTxtFieldMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign On");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Confirm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Delete");

        CodigoETxtField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CodigoETxtField.setForeground(new java.awt.Color(153, 153, 153));
        CodigoETxtField.setText("ID");
        CodigoETxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodigoETxtFieldMouseClicked(evt);
            }
        });

        HackatonList1.setBackground(new java.awt.Color(133, 35, 35));
        HackatonList1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HackatonList1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(HackatonList1);

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HACKATHON CR");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Visualization");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create");

        CodigoTxtField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CodigoTxtField.setForeground(new java.awt.Color(153, 153, 153));
        CodigoTxtField.setText("ID");
        CodigoTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodigoTxtFieldMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Update");

        jButton4.setBackground(new java.awt.Color(102, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Show");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        NombreTxtField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField.setText("Name");
        NombreTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtFieldMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Name");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("ID");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        imagenLabel1.setBackground(new java.awt.Color(133, 35, 35));
        imagenLabel1.setForeground(new java.awt.Color(255, 255, 255));
        imagenLabel1.setText("                                     POSTER");
        imagenLabel1.setOpaque(true);

        BuscarBtn1.setBackground(new java.awt.Color(102, 0, 0));
        BuscarBtn1.setForeground(new java.awt.Color(255, 255, 255));
        BuscarBtn1.setText("Search Image");
        BuscarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtn1ActionPerformed(evt);
            }
        });

        NombreTxtField3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField3.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField3.setText("Topic");
        NombreTxtField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtField3MouseClicked(evt);
            }
        });

        NombreTxtField4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField4.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField4.setText("Project Description");
        NombreTxtField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtField4MouseClicked(evt);
            }
        });

        NombreTxtField7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField7.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField7.setText("Start Date");
        NombreTxtField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtField7MouseClicked(evt);
            }
        });

        NombreTxtField8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField8.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField8.setText("Finish Date");
        NombreTxtField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtField8MouseClicked(evt);
            }
        });

        NombreTxtField9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField9.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField9.setText("Hours");
        NombreTxtField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtField9MouseClicked(evt);
            }
        });

        NombreTxtField10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField10.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField10.setText("Website");
        NombreTxtField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtField10MouseClicked(evt);
            }
        });

        NombreTxtField11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField11.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField11.setText("E-mail");
        NombreTxtField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtField11MouseClicked(evt);
            }
        });

        NombreTxtField12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField12.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField12.setText("1st Place Prize");
        NombreTxtField12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtField12MouseClicked(evt);
            }
        });

        NombreTxtField13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField13.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField13.setText("2nd Place Prize");
        NombreTxtField13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtField13MouseClicked(evt);
            }
        });

        NombreTxtField14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField14.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField14.setText("3rd Place Prize");
        NombreTxtField14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtField14MouseClicked(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Sign on (More Attendants)");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Sign on (More requirements)");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Sign On (More Sponsors)");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("Category");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("Hours");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton12.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("Description");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton13.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("Start Date");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton14.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setText("Website");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton15.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("E-mail");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton17);
        jRadioButton17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton17.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton17.setText("Finish Date");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("1st Prize");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("3rd Prize");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton19);
        jRadioButton19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton19.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton19.setText("2nd Prize");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Logo");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton18);
        jRadioButton18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton18.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton18.setText("Poster");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Organizer" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attendant" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Category" }));
        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox4MouseClicked(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sponsor" }));
        jComboBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox5MouseClicked(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        NombreTxtField5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NombreTxtField5.setForeground(new java.awt.Color(153, 153, 153));
        NombreTxtField5.setText("Requirement");
        NombreTxtField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreTxtField5MouseClicked(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(102, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Show Images");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(102, 0, 0));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Sign On (More editions)");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        EdicionTxtField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EdicionTxtField.setForeground(new java.awt.Color(153, 153, 153));
        EdicionTxtField.setText("#Edicion");
        EdicionTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdicionTxtFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(CodigoETxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jRadioButton1)
                                                            .addComponent(jRadioButton3)
                                                            .addComponent(jRadioButton2))
                                                        .addGap(67, 67, 67)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jRadioButton12)
                                                            .addComponent(jRadioButton10)
                                                            .addComponent(jRadioButton11)))
                                                    .addComponent(jRadioButton7))
                                                .addGap(64, 64, 64)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton17)
                                                    .addComponent(jRadioButton14)
                                                    .addComponent(jRadioButton13)
                                                    .addComponent(jRadioButton15)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CodigoMTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ValorMTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jRadioButton4))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jRadioButton19)))
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton8)
                                                    .addComponent(jRadioButton18)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NombreTxtField7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NombreTxtField8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NombreTxtField10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NombreTxtField11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NombreTxtField12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NombreTxtField13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NombreTxtField14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(EdicionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BuscarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imagenLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(CodigoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NombreTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(14, 14, 14)
                                    .addComponent(NombreTxtField3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NombreTxtField4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NombreTxtField5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(14, 14, 14)
                                    .addComponent(NombreTxtField9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 1257, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTxtField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTxtField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTxtField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTxtField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreTxtField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTxtField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTxtField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTxtField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTxtField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTxtField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreTxtField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EdicionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton5)
                                    .addComponent(jButton6)
                                    .addComponent(jButton7)
                                    .addComponent(jButton9))
                                .addGap(40, 40, 40)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CodigoETxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jRadioButton8)
                                                .addComponent(jRadioButton4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jRadioButton2)
                                                    .addComponent(jRadioButton12)
                                                    .addComponent(jRadioButton13))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jRadioButton1)
                                                    .addComponent(jRadioButton17)
                                                    .addComponent(jRadioButton18)
                                                    .addComponent(jRadioButton10)
                                                    .addComponent(jRadioButton19))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jRadioButton3)
                                                    .addComponent(jRadioButton14)
                                                    .addComponent(jRadioButton11)
                                                    .addComponent(jRadioButton6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jRadioButton15)
                                                    .addComponent(jRadioButton7))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CodigoMTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ValorMTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BuscarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imagenLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton8))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(imagenLabel.getWidth(),imagenLabel.getHeight(),Image.SCALE_SMOOTH));
        imagenLabel.setIcon(imageIcon);
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum;(readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            person_image=bos.toByteArray();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void CodigoMTxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodigoMTxtFieldMouseClicked
        CodigoMTxtField.setText("");
        CodigoMTxtField.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoMTxtFieldMouseClicked

    private void ValorMTxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ValorMTxtFieldMouseClicked
        ValorMTxtField.setText("");
        ValorMTxtField.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorMTxtFieldMouseClicked

    private void CodigoETxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodigoETxtFieldMouseClicked
        CodigoETxtField.setText("");
        CodigoETxtField.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoETxtFieldMouseClicked

    private void CodigoTxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodigoTxtFieldMouseClicked
        CodigoTxtField.setText("");
        CodigoTxtField.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoTxtFieldMouseClicked

    private void NombreTxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtFieldMouseClicked
        NombreTxtField.setText("");
        NombreTxtField.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtFieldMouseClicked

    private void BuscarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtn1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename2 = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename2).getImage().getScaledInstance(imagenLabel1.getWidth(),imagenLabel1.getHeight(),Image.SCALE_SMOOTH));
        imagenLabel1.setIcon(imageIcon);
        try{
            File image = new File(filename2);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum;(readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            person_image2=bos.toByteArray();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_BuscarBtn1ActionPerformed

    private void NombreTxtField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtField4MouseClicked
        NombreTxtField4.setText("");
        NombreTxtField4.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtField4MouseClicked

    private void NombreTxtField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtField7MouseClicked
        NombreTxtField7.setText("");
        NombreTxtField7.setForeground(Color.BLACK);
// TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtField7MouseClicked

    private void NombreTxtField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtField8MouseClicked
        NombreTxtField8.setText("");
        NombreTxtField8.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtField8MouseClicked

    private void NombreTxtField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtField9MouseClicked
        NombreTxtField9.setText("");
        NombreTxtField9.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtField9MouseClicked

    private void NombreTxtField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtField10MouseClicked
        NombreTxtField10.setText("");
        NombreTxtField10.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtField10MouseClicked

    private void NombreTxtField11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtField11MouseClicked
        NombreTxtField11.setText("");
        NombreTxtField11.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtField11MouseClicked

    private void NombreTxtField12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtField12MouseClicked
        NombreTxtField12.setText("");
        NombreTxtField12.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtField12MouseClicked

    private void NombreTxtField13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtField13MouseClicked
        NombreTxtField13.setText("");
        NombreTxtField13.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtField13MouseClicked

    private void NombreTxtField14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtField14MouseClicked
        NombreTxtField14.setText("");
        NombreTxtField14.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtField14MouseClicked

    private void NombreTxtField15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtField15MouseClicked
        NombreTxtField15.setText("");
        NombreTxtField15.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtField15MouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        ValorMTxtField.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        ValorMTxtField.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        ValorMTxtField.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        jComboBox1.removeAllItems();
        try{
            Visualizacion hackathons = new Visualizacion();
            ArrayList<String> listaIds = hackathons.OrganizerCode();
            while(listaIds.isEmpty()==false){
                jComboBox1.addItem(listaIds.get(0));
                listaIds.remove(0);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        jComboBox2.removeAllItems();
        try{
            Visualizacion hackathons = new Visualizacion();
            ArrayList<String> listaIds = hackathons.AttendantID();
            while(listaIds.isEmpty()==false){
                jComboBox2.addItem(listaIds.get(0));
                listaIds.remove(0);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void NombreTxtField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtField3MouseClicked
        NombreTxtField3.setText("");
        NombreTxtField3.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtField3MouseClicked

    private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseClicked
        jComboBox4.removeAllItems();
        try{
            Visualizacion hackathons = new Visualizacion();
            ArrayList<String> listaIds = hackathons.CategoryID();
            while(listaIds.isEmpty()==false){
                jComboBox4.addItem(listaIds.get(0));
                listaIds.remove(0);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4MouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MouseClicked
        jComboBox5.removeAllItems();
        try{
            Visualizacion hackathons = new Visualizacion();
            ArrayList<String> listaIds = hackathons.SponsorCode();
            while(listaIds.isEmpty()==false){
                jComboBox5.addItem(listaIds.get(0));
                listaIds.remove(0);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5MouseClicked

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void NombreTxtField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreTxtField5MouseClicked
        NombreTxtField5.setText("");
        NombreTxtField5.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtField5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Conexion cone = new Conexion();
            Connection con = cone.Conexion();
            String query = "insert into Hackathon(id, name, codOrg, topic, descriptionH, idCat, startDate, finishDate, "
                    + "hours, logo, poster, website, email, prize1, prize2, prize3, sponsorCode) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, CodigoTxtField.getText());
            pst.setString(2, NombreTxtField.getText());
            pst.setString(3, jComboBox1.getSelectedItem().toString());
            pst.setString(4, NombreTxtField3.getText());
            pst.setString(5, NombreTxtField4.getText());
            pst.setString(6, jComboBox4.getSelectedItem().toString());
            pst.setString(7, NombreTxtField7.getText());
            pst.setString(8, NombreTxtField8.getText());
            pst.setString(9, NombreTxtField9.getText());
            pst.setBytes(10, person_image);
            pst.setBytes(11, person_image2);
            pst.setString(12, NombreTxtField10.getText());
            pst.setString(13, NombreTxtField11.getText());
            pst.setString(14, NombreTxtField12.getText());
            pst.setString(15, NombreTxtField13.getText());
            pst.setString(16, NombreTxtField14.getText());
            pst.setString(17, jComboBox5.getSelectedItem().toString());
            pst.executeUpdate();                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            Conexion cone = new Conexion();
            Connection con = cone.Conexion();
            String query = "insert into SponsorHackathon(idHack, codeSponsor) values(?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, CodigoTxtField.getText());
            pst.setString(2, jComboBox5.getSelectedItem().toString());
            pst.executeUpdate();            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            Conexion cone = new Conexion();
            Connection con = cone.Conexion();
            String query = "insert into AttendantHackathon(idHackathon, attendantID) values(?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, CodigoTxtField.getText());
            pst.setString(2, jComboBox2.getSelectedItem().toString());
            pst.executeUpdate();            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            Conexion cone = new Conexion();
            Connection con = cone.Conexion();
            String query = "insert into requirement(idHackathon, nameR) values(?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, CodigoTxtField.getText());
            pst.setString(2, NombreTxtField5.getText());
            pst.executeUpdate();            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            Conexion cone = new Conexion();
            Connection con = cone.Conexion();
            String query = "Insert into Edition(idHackathon, edition) values(?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, CodigoTxtField.getText());
            pst.setString(2, EdicionTxtField.getText());
            pst.executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            Conexion cone = new Conexion();
            Connection con = cone.Conexion();
            String query = "insert into AttendantHackathon(idHackathon, attendantID) values(?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, CodigoTxtField.getText());
            pst.setString(2, jComboBox2.getSelectedItem().toString());
            pst.executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            Conexion cone = new Conexion();
            Connection con = cone.Conexion();
            String query = "insert into SponsorHackathon(idHack, codeSponsor) values(?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, CodigoTxtField.getText());
            pst.setString(2, jComboBox5.getSelectedItem().toString());
            pst.executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            Conexion cone = new Conexion();
            Connection con = cone.Conexion();
            String query = "insert into requirement(idHackathon, nameR) values(?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, CodigoTxtField.getText());
            pst.setString(2, NombreTxtField5.getText());
            pst.executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Eliminacion delete = new Eliminacion();
            delete.Hackathon(CodigoETxtField.getText());
            delete.AttendantHackathon(CodigoETxtField.getText());
            delete.Requirement(CodigoETxtField.getText());
            delete.SponsorHackathon(CodigoETxtField.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String column = "";
        if(jRadioButton2.isSelected()){
            column = "id";
            try{
                Modificar modify = new Modificar();                
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else if(jRadioButton1.isSelected()){
            column = "name";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
        }else if(jRadioButton3.isSelected()){
            column = "codOrg";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else if(jRadioButton7.isSelected()){
            column = "topic";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
        }else if(jRadioButton12.isSelected()){
            column = "descriptionH";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            } 
        }else if(jRadioButton10.isSelected()){
            column = "idCat";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
        }else if(jRadioButton11.isSelected()){
            column = "hours";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
        }else if(jRadioButton13.isSelected()){
            column = "startDate";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
        }else if(jRadioButton17.isSelected()){
            column = "finishDate";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
        }else if(jRadioButton14.isSelected()){
            column = "website";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
        }else if(jRadioButton15.isSelected()){
            column = "email";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
        }else if(jRadioButton4.isSelected()){
            column = "prize1";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
        }else if(jRadioButton19.isSelected()){
            column = "prize2";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
        }else if(jRadioButton6.isSelected()){
            column = "prize3";
            try{
                Modificar modify = new Modificar();
                modify.Hackathon(column, ValorMTxtField.getText(), CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }        
        }else if(jRadioButton8.isSelected()){
            column = "logo";
            try{
                Modificar modify = new Modificar();
                modify.EncargadoImagen(column, person_image, CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else if(jRadioButton18.isSelected()){
            column = "poster";
            try{
                Modificar modify = new Modificar();
                modify.EncargadoImagen(column, person_image2, CodigoMTxtField.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            DefaultListModel model = new DefaultListModel();
            HackatonList1.setModel(model);
            Visualizacion view = new Visualizacion();
            ArrayList<String>listaHackathon=view.Hackathon();
            for (int i = 0; i < listaHackathon.size(); i++) {
                model.add(i, listaHackathon.get(i));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try{
            Conexion con = new Conexion();
            Connection cone = con.Conexion();
            Statement stmt = cone.createStatement();
            String idCat = HackatonList1.getSelectedValue();
            String query = "select Hackathon.logo from Hackathon\n" +
            "join AttendantHackathon on AttendantHackathon.idHackathon = Hackathon.id\n" +
            "join requirement on requirement.idHackathon = Hackathon.id\n" +
            "join Organizer on Organizer.code = Hackathon.codOrg\n" +
            "join Attendant on Attendant.idCard = AttendantHackathon.attendantID\n" +
            "join Category on Category.id = Hackathon.idCat\n" +
            "join Sponsor on Sponsor.code = Hackathon.sponsorCode\n" +
            "where(CONCAT(Hackathon.id,' ',Hackathon.name,' ',Organizer.nameO,' ',Attendant.nameA,' ',topic,' ',\n" +
            "descriptionH,' ',requirement.nameR,' ',Category.name,' ',startDate,' ',finishDate,' ',hours,' ',Hackathon.website,' ',\n" +
            "Hackathon.email,' ',prize1,' ',prize2,' ',prize3,' ',Sponsor.name)='"+idCat+"')";
            ResultSet result =stmt.executeQuery(query);
            
            String query2 = "select Hackathon.poster from Hackathon\n" +
            "join AttendantHackathon on AttendantHackathon.idHackathon = Hackathon.id\n" +
            "join requirement on requirement.idHackathon = Hackathon.id\n" +
            "join Organizer on Organizer.code = Hackathon.codOrg\n" +
            "join Attendant on Attendant.idCard = AttendantHackathon.attendantID\n" +
            "join Category on Category.id = Hackathon.idCat\n" +
            "join Sponsor on Sponsor.code = Hackathon.sponsorCode\n" +
            "where(CONCAT(Hackathon.id,' ',Hackathon.name,' ',Organizer.nameO,' ',Attendant.nameA,' ',topic,' ',\n" +
            "descriptionH,' ',requirement.nameR,' ',Category.name,' ',startDate,' ',finishDate,' ',hours,' ',Hackathon.website,' ',\n" +
            "Hackathon.email,' ',prize1,' ',prize2,' ',prize3,' ',Sponsor.name)='"+idCat+"')";
            ResultSet result2 = stmt.executeQuery(query2);
            while(result.next()==true){
                byte[] img = (result.getBytes("logo"));
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(imagenLabel.getWidth(),imagenLabel.getHeight(),Image.SCALE_SMOOTH));
                imagenLabel.setIcon(imageIcon);
            }
            
            while(result2.next()==true){
                byte[] img = (result2.getBytes("poster"));
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(imagenLabel1.getWidth(),imagenLabel1.getHeight(),Image.SCALE_SMOOTH));
                imagenLabel1.setIcon(imageIcon);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try{
            Conexion cone = new Conexion();
            Connection con = cone.Conexion();
            String query = "insert into Edition(idHackathon, edition) values(?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, CodigoTxtField.getText());
            pst.setString(2, EdicionTxtField.getText());
            pst.executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void EdicionTxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdicionTxtFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EdicionTxtFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hackathon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hackathon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hackathon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hackathon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hackathon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JButton BuscarBtn1;
    private javax.swing.JTextField CodigoETxtField;
    private javax.swing.JTextField CodigoMTxtField;
    private javax.swing.JTextField CodigoTxtField;
    private javax.swing.JTextField EdicionTxtField;
    private javax.swing.JList<String> HackatonList1;
    private javax.swing.JTextField NombreTxtField;
    private javax.swing.JTextField NombreTxtField10;
    private javax.swing.JTextField NombreTxtField11;
    private javax.swing.JTextField NombreTxtField12;
    private javax.swing.JTextField NombreTxtField13;
    private javax.swing.JTextField NombreTxtField14;
    private javax.swing.JTextField NombreTxtField15;
    private javax.swing.JTextField NombreTxtField3;
    private javax.swing.JTextField NombreTxtField4;
    private javax.swing.JTextField NombreTxtField5;
    private javax.swing.JTextField NombreTxtField7;
    private javax.swing.JTextField NombreTxtField8;
    private javax.swing.JTextField NombreTxtField9;
    private javax.swing.JTextField ValorMTxtField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel imagenLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
